server:
  port: 8099 # Spring boot Server port

spring:
  h2:
    console:
      enable: true
      path: /test_db

  datasource:
    driver-class-name: org.h2.Driver
    # Mac
    # url: jdbc:h2:file:D:\h2database\test_db;AUTO_SERVER=TRUE

    # Windows
    url: jdbc:h2:file:D:\h2database\test_db;AUTO_SERVER=TRUE
    username: test
    password: 1234

